# Generated by Django 6.0.4 on 2026-04-26 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vuelos', '0003_rename_capacidad_ejecutiva_aeronave_asientos_economica_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(blank=True, default='', max_length=100)),
                ('tipo_documento', models.CharField(choices=[('ci', 'Cedula de Identidad'), ('pasaporte', 'Pasaporte'), ('otro', 'Otro')], default='ci', max_length=20)),
                ('nro_documento', models.CharField(max_length=30, unique=True)),
                ('correo', models.EmailField(blank=True, max_length=150, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('nacionalidad', models.CharField(blank=True, default='boliviana', max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
                'ordering': ['apellido_paterno', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_reserva', models.CharField(editable=False, max_length=20, unique=True)),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de pago'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('expirada', 'Expirada')], default='pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_asiento_vuelo', models.OneToOneField(db_column='id_asiento_vuelo', on_delete=django.db.models.deletion.CASCADE, related_name='reserva', to='vuelos.asientovuelo')),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='reservas.cliente')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'reserva',
                'ordering': ['-fecha_reserva'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id_ticket', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_ticket', models.CharField(editable=False, max_length=20, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('qr', 'QR Libelula'), ('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta')], default='qr', max_length=20)),
                ('id_transaccion', models.CharField(blank=True, max_length=100, null=True)),
                ('url_pasarela', models.TextField(blank=True, null=True)),
                ('qr_url', models.TextField(blank=True, null=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('emitido', 'Emitido'), ('anulado', 'Anulado'), ('usado', 'Usado')], default='emitido', max_length=20)),
                ('id_reserva', models.OneToOneField(db_column='id_reserva', on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='reservas.reserva')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'db_table': 'ticket',
                'ordering': ['-fecha_emision'],
            },
        ),
    ]
