# Generated by Django 6.0.4 on 2026-05-04 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='canal',
            field=models.CharField(choices=[('caja', 'Caja / Agente'), ('online', 'Plataforma Web')], default='caja', max_length=10),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_cancelacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='detalle_efectivo',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='monto_recibido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='vuelto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='metodo_pago',
            field=models.CharField(choices=[('qr_caja', 'QR Libélula — Caja'), ('qr_online', 'QR Libélula — Online'), ('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta')], default='qr_caja', max_length=20),
        ),
    ]
