# Generated by Django 6.0.4 on 2026-05-04 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_reserva_canal_reserva_fecha_cancelacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_venta', models.CharField(editable=False, max_length=20, unique=True)),
                ('canal', models.CharField(choices=[('caja', 'Caja / Agente'), ('online', 'Plataforma Web')], default='caja', max_length=10)),
                ('metodo_pago', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('qr_caja', 'QR Libélula — Caja'), ('qr_online', 'QR Libélula — Online')], max_length=20, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('monto_recibido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vuelto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('detalle_efectivo', models.JSONField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Venta',
                'db_table': 'venta',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='reserva',
            name='id_venta',
            field=models.ForeignKey(blank=True, db_column='id_venta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='reservas.venta'),
        ),
    ]
