# Generated by Django 6.0.4 on 2026-05-05 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_venta_reserva_id_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.CharField(choices=[('emitido', 'Emitido — pendiente de pago QR'), ('pagado', 'Pagado'), ('anulado', 'Anulado'), ('usado', 'Usado')], default='emitido', max_length=20),
        ),
    ]
