# Generated by Django 6.0.4 on 2026-04-29 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservas', '0001_initial'),
        ('vuelos', '0004_programacionvuelo_ocupacion_minima_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id_devolucion', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.CharField(choices=[('cliente_cancela', 'Cliente cancela voluntariamente'), ('meteorologia', 'Cancelación por meteorología — BOA'), ('falta_cupos', 'Cancelación por falta de cupos — BOA'), ('administracion', 'Cancelación administrativa — BOA')], max_length=30)),
                ('porcentaje_reembolso', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('monto_original', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_reembolso', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de procesar'), ('procesada', 'Procesada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_procesado', models.DateTimeField(blank=True, null=True)),
                ('id_ticket', models.OneToOneField(db_column='id_ticket', on_delete=django.db.models.deletion.CASCADE, related_name='devolucion', to='reservas.ticket')),
            ],
            options={
                'verbose_name': 'Devolución',
                'db_table': 'devolucion',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id_salida', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('abordando', 'En proceso de abordaje'), ('cerrada', 'Cerrada — vuelo en ruta'), ('cancelada', 'Cancelada'), ('reprogramada', 'Reprogramada')], default='programada', max_length=20)),
                ('fecha_salida_real', models.DateField(blank=True, null=True)),
                ('hora_salida_real', models.TimeField(blank=True, null=True)),
                ('motivo_cancelacion', models.CharField(blank=True, choices=[('meteorologia', 'Condiciones meteorológicas'), ('falta_cupos', 'Falta de cupos mínimos'), ('administracion', 'Decisión administrativa BOA')], max_length=20, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_programacion', models.OneToOneField(db_column='id_programacion', on_delete=django.db.models.deletion.CASCADE, related_name='salida', to='vuelos.programacionvuelo')),
            ],
            options={
                'verbose_name': 'Salida',
                'db_table': 'salida',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DetalleAbordaje',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('abordado', models.BooleanField(default=False)),
                ('hora_abordaje', models.TimeField(blank=True, null=True)),
                ('id_reserva', models.ForeignKey(db_column='id_reserva', on_delete=django.db.models.deletion.CASCADE, related_name='detalle_abordaje', to='reservas.reserva')),
                ('id_salida', models.ForeignKey(db_column='id_salida', on_delete=django.db.models.deletion.CASCADE, related_name='detalles_abordaje', to='salida.salida')),
            ],
            options={
                'verbose_name': 'Detalle de Abordaje',
                'db_table': 'detalle_abordaje',
                'unique_together': {('id_salida', 'id_reserva')},
            },
        ),
    ]
