# Generated by Django 6.0.4 on 2026-04-24 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aeronave',
            fields=[
                ('id_aeronave', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_aeronave', models.CharField(max_length=20, unique=True)),
                ('modelo', models.CharField(max_length=100)),
                ('capacidad_turista', models.IntegerField(default=0)),
                ('capacidad_ejecutiva', models.IntegerField(default=0)),
                ('estado', models.CharField(default='activo', max_length=20)),
            ],
            options={
                'verbose_name': 'Aeronave',
                'verbose_name_plural': 'Aeronaves',
                'db_table': 'aeronave',
                'ordering': ['modelo'],
            },
        ),
        migrations.CreateModel(
            name='Aeropuerto',
            fields=[
                ('id_aeropuerto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('ciudad', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('tipo', models.CharField(default='nacional', max_length=20)),
                ('estado', models.CharField(default='activo', max_length=20)),
            ],
            options={
                'verbose_name': 'Aeropuerto',
                'verbose_name_plural': 'Aeropuertos',
                'db_table': 'aeropuerto',
                'ordering': ['ciudad'],
            },
        ),
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id_escala', models.AutoField(primary_key=True, serialize=False)),
                ('ciudad', models.CharField(max_length=100)),
                ('orden', models.IntegerField()),
                ('tiempo_duracion', models.IntegerField(default=0)),
                ('aeropuerto', models.ForeignKey(db_column='id_aeropuerto', on_delete=django.db.models.deletion.CASCADE, related_name='escalas', to='vuelos.aeropuerto')),
            ],
            options={
                'verbose_name': 'Escala',
                'db_table': 'escala',
                'ordering': ['id_ruta', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='ProgramacionVuelo',
            fields=[
                ('id_programacion', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_vuelo', models.CharField(max_length=20, unique=True)),
                ('fecha_salida', models.DateField()),
                ('hora_salida', models.TimeField()),
                ('fecha_llegada', models.DateField()),
                ('hora_llegada', models.TimeField()),
                ('asientos_disponible', models.IntegerField(default=0)),
                ('asiento_vendido', models.IntegerField(default=0)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('en_vuelo', 'En Vuelo'), ('aterrizado', 'Aterrizado'), ('cancelado', 'Cancelado'), ('retrasado', 'Retrasado')], default='programado', max_length=20)),
                ('id_aeronave', models.ForeignKey(db_column='id_aeronave', on_delete=django.db.models.deletion.CASCADE, related_name='programaciones', to='vuelos.aeronave')),
                ('id_escala', models.ForeignKey(blank=True, db_column='id_escala', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programaciones', to='vuelos.escala')),
            ],
            options={
                'verbose_name': 'Programacion de Vuelo',
                'db_table': 'programacion_vuelo',
                'ordering': ['fecha_salida', 'hora_salida'],
            },
        ),
        migrations.CreateModel(
            name='Itinerario',
            fields=[
                ('id_itinerario', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_salida', models.DateField()),
                ('fecha_llegada', models.DateField()),
                ('duracion_total', models.IntegerField(default=0)),
                ('tipo', models.CharField(choices=[('directo', 'Directo'), ('con_escala', 'Con Escala')], default='directo', max_length=20)),
                ('estado', models.CharField(default='activo', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_programacion', models.ForeignKey(db_column='id_programacion', on_delete=django.db.models.deletion.CASCADE, related_name='itinerarios', to='vuelos.programacionvuelo')),
            ],
            options={
                'verbose_name': 'Itinerario',
                'db_table': 'itinerario',
                'ordering': ['fecha_salida'],
            },
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id_ruta', models.AutoField(primary_key=True, serialize=False)),
                ('distancia_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('duracion_hr', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tipo', models.CharField(choices=[('nacional', 'Nacional'), ('internacional', 'Internacional')], default='nacional', max_length=20)),
                ('estado', models.CharField(default='activo', max_length=20)),
                ('id_aeropuerto_destino', models.ForeignKey(db_column='id_aeropuerto_destino', on_delete=django.db.models.deletion.CASCADE, related_name='rutas_destino', to='vuelos.aeropuerto')),
                ('id_aeropuerto_origen', models.ForeignKey(db_column='id_aeropuerto_origen', on_delete=django.db.models.deletion.CASCADE, related_name='rutas_origen', to='vuelos.aeropuerto')),
            ],
            options={
                'verbose_name': 'Ruta',
                'db_table': 'ruta',
                'ordering': ['id_aeropuerto_origen__ciudad'],
                'unique_together': {('id_aeropuerto_origen', 'id_aeropuerto_destino')},
            },
        ),
        migrations.AddField(
            model_name='programacionvuelo',
            name='id_ruta',
            field=models.ForeignKey(db_column='id_ruta', on_delete=django.db.models.deletion.CASCADE, related_name='programaciones', to='vuelos.ruta'),
        ),
        migrations.AddField(
            model_name='escala',
            name='id_ruta',
            field=models.ForeignKey(db_column='id_ruta', on_delete=django.db.models.deletion.CASCADE, related_name='escalas', to='vuelos.ruta'),
        ),
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id_asiento', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=5)),
                ('fila', models.IntegerField()),
                ('clase', models.CharField(choices=[('economica', 'Económica'), ('economica_premium', 'Económica Premium'), ('ejecutiva', 'Ejecutiva'), ('primera_clase', 'Primera Clase')], default='economica', max_length=20)),
                ('estado', models.CharField(default='activo', max_length=20)),
                ('id_aeronave', models.ForeignKey(db_column='id_aeronave', on_delete=django.db.models.deletion.CASCADE, related_name='asientos', to='vuelos.aeronave')),
            ],
            options={
                'verbose_name': 'Asiento',
                'db_table': 'asiento',
                'ordering': ['fila', 'numero'],
                'unique_together': {('id_aeronave', 'numero')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='escala',
            unique_together={('id_ruta', 'orden')},
        ),
    ]
