# Generated by Django 6.0.4 on 2026-04-22 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aeronave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_aeronave', models.CharField(max_length=20, unique=True)),
                ('modelo', models.CharField(max_length=100)),
                ('capacidad_ejecutiva', models.IntegerField(default=0)),
                ('capacidad_turista', models.IntegerField(default=0)),
                ('estado', models.CharField(default='activa', max_length=20)),
            ],
            options={
                'db_table': 'aeronave',
            },
        ),
        migrations.CreateModel(
            name='Aeropuerto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('ciudad', models.CharField(max_length=100)),
                ('tipo', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'db_table': 'aeropuerto',
            },
        ),
        migrations.CreateModel(
            name='Itinerario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('fecha_salida', models.DateTimeField()),
                ('fecha_llegada', models.DateTimeField()),
                ('duracion_total', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('estado', models.CharField(default='programado', max_length=20)),
                ('tipo', models.CharField(blank=True, default='', max_length=50)),
                ('observaciones', models.CharField(blank=True, default='', max_length=500)),
            ],
            options={
                'db_table': 'itinerario',
            },
        ),
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('fila', models.CharField(max_length=5)),
                ('clase', models.CharField(max_length=50)),
                ('estado', models.CharField(default='disponible', max_length=20)),
                ('id_aeronave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asientos', to='vuelos.aeronave')),
            ],
            options={
                'db_table': 'asiento',
            },
        ),
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(blank=True, default='', max_length=100)),
                ('orden', models.IntegerField()),
                ('tiempo_duracion', models.IntegerField(blank=True, null=True)),
                ('id_aeropuerto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vuelos.aeropuerto')),
                ('id_escala_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalas_siguientes', to='vuelos.escala')),
            ],
            options={
                'db_table': 'escala',
            },
        ),
        migrations.CreateModel(
            name='ProgramacionVuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_vuelo', models.CharField(max_length=20, unique=True)),
                ('fecha_salida', models.DateTimeField()),
                ('fecha_llegada', models.DateTimeField()),
                ('hora_salida', models.TimeField()),
                ('hora_llegada', models.TimeField()),
                ('asientos_disponible', models.IntegerField(default=0)),
                ('asiento_vendido', models.IntegerField(default=0)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(default='programado', max_length=20)),
                ('id_aeronave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programaciones', to='vuelos.aeronave')),
                ('id_escala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programaciones', to='vuelos.escala')),
                ('id_itinerario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programaciones', to='vuelos.itinerario')),
            ],
            options={
                'db_table': 'programacion_vuelo',
            },
        ),
        migrations.CreateModel(
            name='Reprogramacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_anterior', models.DateTimeField()),
                ('fecha_nueva', models.DateTimeField()),
                ('hora_anterior', models.TimeField()),
                ('hora_nueva', models.TimeField()),
                ('motivo', models.CharField(blank=True, default='', max_length=500)),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('id_programacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reprogramacion', to='vuelos.programacionvuelo')),
            ],
            options={
                'db_table': 'reprogramacion',
            },
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distancia_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('duracion_hr', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('estado', models.CharField(default='activa', max_length=20)),
                ('tipo', models.CharField(blank=True, default='', max_length=50)),
                ('id_aeropuerto_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas_destino', to='vuelos.aeropuerto')),
                ('id_aeropuerto_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas_origen', to='vuelos.aeropuerto')),
            ],
            options={
                'db_table': 'ruta',
            },
        ),
        migrations.AddField(
            model_name='programacionvuelo',
            name='id_ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programaciones', to='vuelos.ruta'),
        ),
        migrations.AddField(
            model_name='itinerario',
            name='id_ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerarios', to='vuelos.ruta'),
        ),
        migrations.AddField(
            model_name='escala',
            name='id_ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalas', to='vuelos.ruta'),
        ),
        migrations.CreateModel(
            name='SalidaVuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cupo_actual', models.IntegerField(default=0)),
                ('cupo_minimo', models.IntegerField(default=0)),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.CharField(blank=True, default='', max_length=500)),
                ('id_programacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salida', to='vuelos.programacionvuelo')),
            ],
            options={
                'db_table': 'salida_vuelo',
            },
        ),
        migrations.CreateModel(
            name='Tripulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField()),
                ('observaciones', models.CharField(blank=True, default='', max_length=500)),
                ('id_programacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tripulacion', to='vuelos.programacionvuelo')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tripulaciones', to='seguridad.usuario')),
            ],
            options={
                'db_table': 'tripulacion',
            },
        ),
    ]
