# Generated by Django 6.0.4 on 2026-04-25 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuelos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionPrecio',
            fields=[
                ('id_config', models.AutoField(primary_key=True, serialize=False)),
                ('incremento_economica_premium', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('incremento_ejecutiva', models.DecimalField(decimal_places=2, default=15.0, max_digits=5)),
                ('incremento_primera_clase', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuracion de Precio',
                'db_table': 'configuracion_precio',
            },
        ),
        migrations.CreateModel(
            name='OfertaVuelo',
            fields=[
                ('id_oferta', models.AutoField(primary_key=True, serialize=False)),
                ('clase', models.CharField(choices=[('economica', 'Economica'), ('economica_premium', 'Economica Premium'), ('ejecutiva', 'Ejecutiva'), ('primera_clase', 'Primera Clase')], max_length=20)),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('id_programacion', models.ForeignKey(db_column='id_programacion', on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='vuelos.programacionvuelo')),
            ],
            options={
                'verbose_name': 'Oferta de Vuelo',
                'db_table': 'oferta_vuelo',
            },
        ),
        migrations.CreateModel(
            name='AsientoVuelo',
            fields=[
                ('id_asiento_vuelo', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('reservado', 'Reservado'), ('vendido', 'Vendido'), ('bloqueado', 'Bloqueado')], default='disponible', max_length=20)),
                ('id_asiento', models.ForeignKey(db_column='id_asiento', on_delete=django.db.models.deletion.CASCADE, related_name='asientos_vuelo', to='vuelos.asiento')),
                ('id_programacion', models.ForeignKey(db_column='id_programacion', on_delete=django.db.models.deletion.CASCADE, related_name='asientos_vuelo', to='vuelos.programacionvuelo')),
            ],
            options={
                'verbose_name': 'Asiento de Vuelo',
                'db_table': 'asiento_vuelo',
                'unique_together': {('id_programacion', 'id_asiento')},
            },
        ),
    ]
