# Generated by Django 6.0.4 on 2026-04-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuelos', '0002_configuracionprecio_ofertavuelo_asientovuelo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aeronave',
            old_name='capacidad_ejecutiva',
            new_name='asientos_economica',
        ),
        migrations.RenameField(
            model_name='aeronave',
            old_name='capacidad_turista',
            new_name='asientos_economica_premium',
        ),
        migrations.AddField(
            model_name='aeronave',
            name='asientos_ejecutiva',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aeronave',
            name='asientos_primera_clase',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aeronave',
            name='tipo_pasillo',
            field=models.CharField(choices=[('simple', 'Un pasillo'), ('doble', 'Dos pasillos')], default='simple', max_length=10),
        ),
    ]
