# Generated by Django 6.0.4 on 2026-04-29 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuelos', '0003_rename_capacidad_ejecutiva_aeronave_asientos_economica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacionvuelo',
            name='ocupacion_minima',
            field=models.IntegerField(default=75),
        ),
        migrations.AlterField(
            model_name='programacionvuelo',
            name='estado',
            field=models.CharField(choices=[('programado', 'Programado'), ('en_vuelo', 'En Vuelo'), ('aterrizado', 'Aterrizado'), ('cancelado', 'Cancelado'), ('retrasado', 'Retrasado'), ('reprogramado', 'Reprogramado')], default='programado', max_length=20),
        ),
    ]
