# Generated by Django 6.0.4 on 2026-05-03 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuelos', '0004_programacionvuelo_ocupacion_minima_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aeropuerto',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='aeropuerto',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
