# Generated by Django 6.0.4 on 2026-05-03 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vuelos', '0005_aeropuerto_latitud_aeropuerto_longitud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programacionvuelo',
            name='id_escala',
        ),
    ]
