# Generated by Django 6.0.4 on 2026-05-03 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuelos', '0006_remove_programacionvuelo_id_escala'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoTripulacion',
            fields=[
                ('id_grupo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('asignado', 'Asignado'), ('en_vuelo', 'En Vuelo')], default='disponible', max_length=20)),
            ],
            options={
                'verbose_name': 'Grupo de Tripulación',
                'db_table': 'grupo_tripulacion',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Tripulante',
            fields=[
                ('id_tripulante', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('ci', models.CharField(max_length=20, unique=True)),
                ('cargo', models.CharField(choices=[('piloto', 'Piloto'), ('copiloto', 'Copiloto'), ('auxiliar', 'Auxiliar de Vuelo')], max_length=20)),
                ('estado', models.CharField(choices=[('libre', 'Libre'), ('asignado', 'Asignado'), ('en_vuelo', 'En Vuelo'), ('fuera_de_servicio', 'Fuera de Servicio')], default='libre', max_length=20)),
            ],
            options={
                'verbose_name': 'Tripulante',
                'db_table': 'tripulante',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionGrupo',
            fields=[
                ('id_asignacion', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='activo', max_length=20)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('id_programacion', models.OneToOneField(db_column='id_programacion', on_delete=django.db.models.deletion.CASCADE, related_name='asignacion_grupo', to='vuelos.programacionvuelo')),
                ('id_grupo', models.ForeignKey(db_column='id_grupo', on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='vuelos.grupotripulacion')),
            ],
            options={
                'verbose_name': 'Asignación de Grupo',
                'db_table': 'asignacion_grupo',
                'ordering': ['-fecha_asignacion'],
            },
        ),
        migrations.AddField(
            model_name='grupotripulacion',
            name='tripulantes',
            field=models.ManyToManyField(blank=True, related_name='grupos', to='vuelos.tripulante'),
        ),
    ]
