# Generated by Django 6.0.4 on 2026-05-03 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuelos', '0007_grupotripulacion_tripulante_asignaciongrupo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacionvuelo',
            name='descripcion_cancelacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programacionvuelo',
            name='motivo_cancelacion',
            field=models.CharField(blank=True, choices=[('meteorologia', 'Condiciones Meteorológicas'), ('falta_cupos', 'Falta de Ocupación Mínima'), ('administrativo', 'Decisión Administrativa'), ('falla_tecnica', 'Falla Técnica'), ('otro', 'Otro Motivo')], max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='Reprogramacion',
            fields=[
                ('id_reprogramacion', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.CharField(choices=[('meteorologia', 'Condiciones Meteorológicas'), ('falta_cupos', 'Falta de Ocupación Mínima'), ('administrativo', 'Decisión Administrativa'), ('falla_tecnica', 'Falla Técnica'), ('otro', 'Otro Motivo')], max_length=30)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('reprogramado', 'Reprogramado'), ('cancelado_definitivo', 'Cancelado Definitivo')], default='pendiente', max_length=30)),
                ('nueva_fecha_salida', models.DateField(blank=True, null=True)),
                ('nueva_hora_salida', models.TimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('id_programacion', models.ForeignKey(db_column='id_programacion', on_delete=django.db.models.deletion.CASCADE, related_name='reprogramaciones', to='vuelos.programacionvuelo')),
            ],
            options={
                'verbose_name': 'Reprogramación',
                'db_table': 'reprogramacion',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
