# Generated by Django 6.0.4 on 2026-04-29 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Egreso',
            fields=[
                ('id_egreso', models.AutoField(primary_key=True, serialize=False)),
                ('id_devolucion', models.IntegerField(blank=True, null=True)),
                ('concepto', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('devolucion', 'Devolución de pasaje'), ('operacional', 'Gasto operacional'), ('otro', 'Otro egreso')], default='devolucion', max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Egreso',
                'db_table': 'egreso',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id_ingreso', models.AutoField(primary_key=True, serialize=False)),
                ('concepto', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('venta_pasaje', 'Venta de pasaje'), ('otro', 'Otro ingreso')], default='venta_pasaje', max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_ticket', models.OneToOneField(blank=True, db_column='id_ticket', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingreso', to='reservas.ticket')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'db_table': 'ingreso',
                'ordering': ['-fecha'],
            },
        ),
    ]
