# Generated by Django 6.0.4 on 2026-05-06 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
        ('reservas', '0004_alter_ticket_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='id_ticket',
            field=models.OneToOneField(blank=True, db_column='id_ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingreso', to='reservas.ticket'),
        ),
    ]
