from .aeropuerto import Aeropuerto
from .ruta import Ruta
from .escala import Escala
from .aeronave import Aeronave
from .asiento import Asiento
from .itinerario import Itinerario
from .programacion_vuelo import ProgramacionVuelo
from .tripulacion import Tripulacion
from .salida_vuelo import SalidaVuelo
from .reprogramacion import Reprogramacion