# Generated by Django 6.0.4 on 2026-04-29 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(choices=[('reprogramacion', 'Reprogramación de vuelo'), ('cancelacion', 'Cancelación de vuelo'), ('confirmacion_pago', 'Confirmación de pago'), ('devolucion', 'Devolución procesada'), ('abordaje', 'Recordatorio de abordaje'), ('general', 'General')], default='general', max_length=30)),
                ('id_usuario', models.IntegerField(blank=True, null=True)),
                ('id_cliente', models.IntegerField(blank=True, null=True)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('referencia_id', models.IntegerField(blank=True, null=True)),
                ('referencia_tipo', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Notificación',
                'db_table': 'notificacion',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
