# Generated by Django 6.0.4 on 2026-04-22 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('trabajador', 'Trabajador'), ('pasajero', 'Pasajero')], default='trabajador', max_length=20),
        ),
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(blank=True, default='', max_length=100)),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
                ('num_telefono', models.CharField(blank=True, default='', max_length=20)),
                ('nacionalidad', models.CharField(blank=True, default='', max_length=100)),
                ('tipo_documento', models.IntegerField(default=1)),
                ('nro_documento', models.CharField(max_length=20, unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pasajero', to='seguridad.usuario')),
            ],
            options={
                'db_table': 'pasajero',
            },
        ),
    ]
